"""Generate sample upstream CSVs.

Produces a history deep enough to exercise the retention rules — you cannot
meaningfully test "10 business days plus 80 month-ends" against three days of
data, and a retention bug that only appears at month boundaries is exactly the
kind that reaches production.

The generated data deliberately includes the awkward cases:

  * a re-delivered business date (_v2), to exercise version handling
  * a day where the counterparty feed is late/absent, to exercise carry-forward
  * a trade referencing a counterparty missing from the reference feed
  * an unparseable notional, to prove the load lands and the TEST fails
  * a new upstream column appearing partway through, to exercise schema drift
  * mixed is_active representations (Y/N/1/0/true)
  * mixed date formats (yyyyMMdd and yyyy-MM-dd)

`--clean` suppresses the two injected *failures* (the orphan counterparty
reference and the unparseable notional) while keeping everything else --
redelivery, the absent feed, schema drift, mixed representations. It exists so
a build can be produced that genuinely passes its tests, which is what a
publish-to-main demonstration needs. Combine with `--version 2` to emit the
clean history as a redelivery of the same business dates: the prepared layer
takes the latest `_file_version`, so the restatement supersedes the bad data
exactly as a real upstream correction would.

Four feeds are generated by the hand-written functions below --  trade,
counterparty and rating -- because their PATHOLOGIES are the
point, and a generator working from a feed definition alone cannot produce
them: the injected failures, the schema drift, the absent delivery, the
non-overlapping SCD2 ranges `dbt_utils.mutually_exclusive_ranges` tests, the
cadence difference between a daily feed and a weekly one.

Every OTHER feed in feeds.yml -- collateral today, and anything added through
the feed console tomorrow -- is generated afterwards by
`reporting_platform.ui.sampledata`, the console's definition-driven generator.
That is not a lesser fallback: for a feed whose interest is that it exists and
joins correctly, deriving the columns from the definition is the more accurate
thing to do, and it means adding a feed does not also mean editing this script.
It runs SECOND because it takes its business dates and its foreign keys from
what the other feeds have already written, and raises on an empty seed
directory.

Usage:
    python scripts/generate_feeds.py --months 30 --out seed/
    python scripts/generate_feeds.py --months 30 --out seed_clean/ --clean --version 2
"""
from __future__ import annotations

import argparse
import os
import csv
import random
import zlib
from datetime import date, timedelta
from pathlib import Path

from reporting_platform.common.volatility import (
    epoch as _epoch, epoch_start as _epoch_start, stable_rng as _stable_rng)

random.seed(20260811)

COUNTRIES = ["GB", "US", "DE", "FR", "JP", "SG", "CH", "NL", "IE", "AU"]
SECTORS = ["BANKS", "INSURANCE", "SOVEREIGN", "CORPORATE", "FUNDS", "CENTRAL_CPTY"]
AGENCIES = ["MOODYS", "SP", "FITCH"]
RATINGS = ["AAA", "AA+", "AA", "AA-", "A+", "A", "A-", "BBB+", "BBB", "BBB-",
           "BB+", "BB", "BB-", "B+", "B"]
PRODUCTS = ["IRS", "CDS", "FXFWD", "REPO", "EQ_SWAP", "OPTION"]
BOOKS = ["LDN_RATES", "LDN_CREDIT", "NY_RATES", "SG_FX", "LDN_EQD"]
CURRENCIES = ["GBP", "USD", "EUR", "JPY", "CHF"]

N_COUNTERPARTIES = 60
N_TRADES = 400

LIMIT_TYPES = ["PRE_SETTLEMENT", "SETTLEMENT", "ISSUER"]

# Slowly-changing values: see reporting_platform/common/volatility.py for what
# was wrong (every attribute redrawn on every delivery) and why the fix is
# shaped the way it is. The helpers live there because the feed console's
# generator needs exactly the same behaviour and two copies of this would
# drift.


# How long each attribute holds still, in days. Named rather than inlined
# because these ARE the realism model for the built-in feeds, and someone
# tuning the seed should be able to see the whole set at once.
HOLD = {
    "cpty_name": 900,        # a rebrand, once or twice in the seed's span
    "cpty_active": 500,      # a name going inactive
    "rating_grade": 260,     # an upgrade or downgrade, roughly yearly
    "rating_outlook": 130,   # outlook moves more often than the grade
    "limit_amount": 180,     # a limit review, roughly twice a year
    "limit_status": 420,     # suspension is rarer still
}


def business_days(start: date, end: date) -> list[date]:
    out, d = [], start
    while d <= end:
        if d.weekday() < 5:
            out.append(d)
        d += timedelta(days=1)
    return out


def counterparty_ids() -> list[str]:
    return [f"CP{i:05d}" for i in range(1, N_COUNTERPARTIES + 1)]


def write_csv(path: Path, header: list[str], rows: list[list]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
        w.writerow(header)
        w.writerows(rows)


def gen_counterparty(bd: date, out: Path, drift: bool, version: int = 1) -> None:
    """Reference data: legal name, domicile, sector, parent, active flag.

    Almost all of this is constant for the life of the counterparty, which is
    what makes it reference data. Two things move, both on long epochs: a
    handful of names rebrand, and a handful of counterparties go inactive.

    The MIXED is_active REPRESENTATIONS ARE KEPT -- Y/N/1/0/true/false across
    the file is what exercises the boolean CASE in the prepared model -- but
    each counterparty now keeps its own representation instead of drawing a
    new one every day. Varying it per name still covers every branch; varying
    it per day only manufactured churn.
    """
    header = ["counterparty_id", "legal_name", "country_code", "sector",
              "parent_counterparty_id", "is_active"]
    if drift:
        # New upstream column appears partway through the history. The pipeline
        # must land it in _extra_columns and warn, not fail.
        header.append("lei_code")

    rows = []
    for i, cid in enumerate(counterparty_ids()):
        # A rebrand: the same legal entity, restated under a new name. Only a
        # few names ever do it, and never on the same day as each other.
        name = f"Counterparty {i + 1} Holdings Ltd"
        if i % 17 == 0 and _epoch(cid, bd, HOLD["cpty_name"], "name") % 2:
            name = f"Counterparty {i + 1} Group PLC"

        # Only the last five can ever go inactive, as before -- but now it is a
        # state that persists for an epoch rather than a coin flip per file.
        active = True
        if i >= N_COUNTERPARTIES - 5:
            active = _stable_rng(cid, "active",
                                 _epoch(cid, bd, HOLD["cpty_active"], "active")
                                 ).random() > 0.4

        truthy = ["Y", "1", "true", "TRUE", "Yes"]
        falsy = ["N", "0", "false"]
        pool = truthy if active else falsy
        active_repr = pool[zlib.crc32(cid.encode()) % len(pool)]

        row = [
            cid,
            name,
            COUNTRIES[i % len(COUNTRIES)],
            SECTORS[i % len(SECTORS)],
            f"CP{((i // 10) * 10 + 1):05d}" if i % 10 else "",
            active_repr,
        ]
        if drift:
            row.append(f"LEI{i:015d}")
        rows.append(row)

    suffix = f"_v{version}" if version > 1 else ""
    write_csv(out / f"CPTY_{bd:%Y%m%d}{suffix}.csv", header, rows)


def gen_rating(bd: date, out: Path, version: int = 1) -> None:
    """Agency ratings: a grade, when it was assigned, and an outlook.

    WHICH agencies rate a name is decided once per (counterparty, agency)
    rather than redrawn per file, so coverage does not flicker. The grade moves
    on a roughly yearly epoch and the outlook about twice as often, which is the
    real relationship between the two.
    See docs/DECISIONS.md#generated-data-must-hold-still

    `rating_date` is now the date the CURRENT GRADE came into force, not the
    business date. A rating_date equal to the delivery date on every row is
    the delivery date under another name, and it guaranteed that every row
    differed from yesterday's even when the rating had not moved.
    """
    header = ["counterparty_id", "agency", "rating", "rating_date", "outlook"]
    rows = []
    for i, cid in enumerate(counterparty_ids()):
        for agency in AGENCIES:
            # Standing coverage, not a per-file coin flip.
            if _stable_rng(cid, agency, "covers").random() < 0.15:
                continue

            # Drift up or down from the name's baseline grade as the epoch
            # advances, staying inside the scale.
            base = (i + AGENCIES.index(agency)) % len(RATINGS)
            move = _stable_rng(cid, agency, "grade",
                               _epoch(cid + agency, bd, HOLD["rating_grade"],
                                      "grade")).randint(-1, 1)
            grade = RATINGS[min(max(base + move, 0), len(RATINGS) - 1)]
            assigned = _epoch_start(cid + agency, bd, HOLD["rating_grade"], "grade")

            outlook = _stable_rng(cid, agency, "outlook",
                                  _epoch(cid + agency, bd, HOLD["rating_outlook"],
                                         "outlook")
                                  ).choice(["STABLE", "STABLE", "POSITIVE",
                                            "NEGATIVE", ""])
            rows.append([
                cid, agency, grade,
                # Mixed date formats on purpose, stable per counterparty.
                assigned.strftime("%Y-%m-%d") if i % 2 else assigned.strftime("%Y%m%d"),
                outlook,
            ])
    suffix = f"_v{version}" if version > 1 else ""
    write_csv(out / f"RATING_{bd:%Y%m%d}{suffix}.csv", header, rows)


def _slot_tenor(slot: int) -> int:
    """Days this slot's trades run for. Fixed per slot, so the book has a
    stable maturity profile rather than a new one every morning."""
    rng = _stable_rng("slot", slot, "tenor")
    roll, acc = rng.randint(1, 100), 0
    for weight, lo, hi in TENORS:
        acc += weight
        if roll <= acc:
            return rng.randint(lo, hi)
    return rng.randint(180, 540)


def gen_trade(bd: date, out: Path, version: int = 1, inject_bad: bool = False,
              clean: bool = False) -> None:
    """A PERSISTING BOOK, not 400 brand-new trades every morning.

    `trade_id` must NOT embed the business date, or every delivery invents a new
    portfolio, nothing can be compared to itself, and `exposure_change` never
    sees an UNCHANGED row. See docs/DECISIONS.md#generated-data-must-hold-still

    Each of the 400 slots holds one trade for its tenor and is refilled at
    maturity. Within a trade's life EVERYTHING IS IMMUTABLE -- counterparty,
    book, product, currency, notional, trade_date, maturity_date -- and only
    `mtm_value` moves, at a frequency set by how much life the trade has left
    (see MTM_HOLD). So a 30-day trade is remarked daily while a ten-year swap
    is byte-identical for a month at a time, which is what the prepared and
    reporting layers should be being asked to cope with.
    """
    header = ["trade_id", "counterparty_id", "book", "product_type", "notional",
              "currency", "trade_date", "maturity_date", "mtm_value"]
    cps = counterparty_ids()
    rows = []
    for t in range(N_TRADES):
        tenor = _slot_tenor(t)
        # The generation of trade currently occupying this slot, and the day it
        # was struck. bd always falls inside [trade_date, maturity].
        gen = _epoch(f"slot{t}", bd, tenor, "book")
        trade_dt = _epoch_start(f"slot{t}", bd, tenor, "book")
        maturity = trade_dt + timedelta(days=tenor - 1)
        tid = f"TRD{t:04d}G{gen:04d}"

        # Everything below is a property of the TRADE, so it is drawn from the
        # trade's identity and cannot move while the trade is alive.
        fixed = _stable_rng(tid, "terms")
        cid = cps[t % len(cps)]
        # One trade per file references a counterparty absent from the
        # reference feed, so the relationships test has something to catch.
        if t == 7 and not clean:
            cid = "CP99999"

        notional = round(fixed.uniform(50_000, 25_000_000), 2)
        notional_str = f"{notional}"
        if inject_bad and t == 13 and not clean:
            notional_str = "N/A"          # must land as NULL and fail a test

        residual = (maturity - bd).days
        hold = next(h for limit, h in MTM_HOLD if residual <= limit)
        mtm = round(_stable_rng(tid, "mtm", _epoch(tid, bd, hold, "mtm")
                                ).uniform(-2_000_000, 5_000_000), 2)
        # Version 2 of a date is a genuine restatement, not a byte-identical
        # resend -- the marks move, the terms do not.
        if version > 1:
            mtm = round(mtm * 1.05, 2)

        rows.append([
            tid,
            cid,
            BOOKS[t % len(BOOKS)],
            PRODUCTS[t % len(PRODUCTS)],
            notional_str,
            CURRENCIES[t % len(CURRENCIES)],
            trade_dt.strftime("%Y-%m-%d") if t % 2 else trade_dt.strftime("%Y%m%d"),
            maturity.strftime("%Y-%m-%d"),
            f"{mtm}",
        ])

    suffix = f"_v{version}" if version > 1 else ""
    write_csv(out / f"TRADE_{bd:%Y%m%d}{suffix}.csv", header, rows)


# The feeds with a hand-written generator in this module. Everything else in
# feeds.yml is generated from its definition -- see the module docstring. This
# is a list of what is implemented here, so it belongs next to the functions;
# deriving it by introspecting `gen_*` names would be clever and would silently
# skip a feed the moment someone renamed one.
HAND_WRITTEN = frozenset({"trade", "counterparty", "rating"})


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--months", type=int, default=30,
                   help="how much history to generate (default 30, enough to "
                        "exercise month-end retention meaningfully)")
    p.add_argument("--end", type=lambda s: date.fromisoformat(s), default=date.today())
    p.add_argument("--out", type=Path, default=Path("seed"))
    p.add_argument("--dense-days", type=int, default=25,
                   help="generate every business day for this many days at the "
                        "end; earlier history is month-ends only, to keep the "
                        "seed directory a sane size")
    p.add_argument("--clean", action="store_true",
                   help="omit the two injected FAILURES (orphan counterparty "
                        "reference, unparseable notional) so the build passes "
                        "its tests. Redelivery, the absent feed, schema drift "
                        "and mixed representations are all still generated.")
    p.add_argument("--version", type=int, default=1,
                   help="emit every file with a _vN suffix, i.e. as a "
                        "redelivery of the same business dates. Use with "
                        "--clean to restate a bad history.")
    a = p.parse_args()

    start = a.end - timedelta(days=int(a.months * 30.44))
    all_days = business_days(start, a.end)
    dense = set(all_days[-a.dense_days:])

    # Month-ends for the sparse portion: last business day of each month.
    by_month: dict[tuple[int, int], date] = {}
    for d in all_days:
        by_month[(d.year, d.month)] = d
    sparse = set(by_month.values())

    days = sorted(dense | sparse)

    # A late/absent counterparty feed on one recent day.
    skip_cpty = sorted(dense)[-3] if len(dense) >= 3 else None
    # Schema drift begins here.
    drift_from = sorted(dense)[-8] if len(dense) >= 8 else None
    # This date gets re-delivered as _v2.
    redeliver = sorted(dense)[-5] if len(dense) >= 5 else None
    # The date carrying the injected unparseable notional. Guarded like the
    # three above -- it was the one `sorted(dense)[-N]` written inline in the
    # loop below instead, so `--dense-days` under 6 died with
    # `IndexError: list index out of range` from inside the generator rather
    # than being told it had asked for too few days. `--dense-days` is a
    # documented, user-facing flag, so any value it accepts has to work.
    # (Hoisting it also stops re-sorting `dense` once per generated day.)
    inject_bad_on = sorted(dense)[-6] if len(dense) >= 6 else None

    for d in days:
        gen_trade(d, a.out / "trade", version=a.version, clean=a.clean,
                  inject_bad=(inject_bad_on is not None and d == inject_bad_on))
        if d != skip_cpty:
            gen_counterparty(d, a.out / "counterparty", version=a.version,
                             drift=bool(drift_from and d >= drift_from))
        if d.weekday() == 0 or d in sparse:      # ratings arrive weekly-ish
            gen_rating(d, a.out / "rating", version=a.version)

    # The deliberate _v2 restatement of one date. Skipped when the whole run is
    # already a versioned redelivery, which would otherwise collide.
    if redeliver and a.version == 1:
        gen_trade(redeliver, a.out / "trade", version=2, clean=a.clean)

    # Feeds with no hand-written generator above, from the console's
    # definition-driven one. Imported HERE rather than at module scope on
    # purpose: sampledata resolves the seed root through feeddata.SEED_DIR,
    # which is bound from REPORTING_SEED_DIR at IMPORT time, so the env var has
    # to be set before the import happens or --out is silently ignored and
    # everything lands in /opt/platform/seed.
    os.environ["REPORTING_SEED_DIR"] = str(a.out)
    from reporting_platform.common.context import feeds            # noqa: E402
    from reporting_platform.ui import sampledata, scaffold         # noqa: E402

    derived = [f for f in feeds().values() if f.name not in HAND_WRITTEN]
    for feed in derived:
        try:
            # days=0 is every business date the other feeds delivered on, not
            # sampledata's default of 3: this is a history generator, and three
            # days of collateral against 30 months of trades would make the
            # joins look broken.
            # types= is NOT optional, for the reason the console's call site
            # in ui/app.py spells out: without it sampledata re-guesses from
            # the column NAME, so `haircut_pct` -- declared `decimal` in
            # feeds.yml -- gets a value like `HAI-4067`, the prepared model's
            # safe_cast nulls the whole column, and nothing fails, because
            # safe_cast nulling is what safe_cast is for. Verified by
            # generating it both ways. resolve_types is the same resolved map
            # the scaffold uses: declared column_types over inferred.
            res = sampledata.generate(feed, days=0,
                                      types=scaffold.resolve_types(feed),
                                      version=a.version if a.version > 1 else None)
            print(f"  {feed.name}: {len(res['written'])} files "
                  f"(from feed definition)")
        except Exception as exc:                                   # noqa: BLE001
            # Not fatal. A definition the generator cannot satisfy should not
            # cost you the four feeds it already wrote -- and the failure needs
            # to be legible, because the usual cause is a feed whose columns
            # reference data no other feed provides.
            print(f"  {feed.name}: NOT generated -- {exc}")

    print(f"generated {len(days)} business dates into {a.out}/")
    print(f"  dense (every business day): {min(dense)}.. {max(dense)}")
    print(f"  sparse (month-ends only):   {min(sparse)}.. {max(sparse)}")
    print(f"  counterparty feed absent:   {skip_cpty}")
    print(f"  schema drift (lei_code) from: {drift_from}")
    print(f"  re-delivered as _v2:        {redeliver if a.version == 1 else 'n/a'}")
    print(f"  injected failures:          {'OMITTED (--clean)' if a.clean else 'present'}")
    print(f"  file version suffix:        {'_v%d' % a.version if a.version > 1 else 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
